# Generated by Django 5.1 on 2024-10-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_person_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='password',
            new_name='username',
        ),
    ]
